from .build_update_views import *
from .fork_view import *
from .commands_view import *
from .command_detail_view import *
from .user_commands_view import *
from .public_commands_view import *
from .install_command_view import *
from .installed_command_view import *
from .update_command_after_train import *
