# Generated by Django 4.1.6 on 2023-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basescript',
            name='state',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=100),
        ),
    ]
