# Generated by Django 4.1.6 on 2023-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_basescript_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basescript',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
