# Generated by Django 4.1.6 on 2023-02-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_basescript_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basescript',
            name='is_reviewed',
        ),
    ]
