# Generated by Django 4.1.6 on 2023-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_basescript_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basescript',
            name='description',
        ),
        migrations.RemoveField(
            model_name='basescript',
            name='state',
        ),
        migrations.AddField(
            model_name='basescript',
            name='dependency',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='basescript',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='basescript',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basescript',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
