# Generated by Django 4.1.6 on 2023-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_basecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecommand',
            name='state',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=100),
        ),
    ]
