# Generated by Django 4.1.6 on 2023-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_basecommand_is_reviewed_basecommand_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecommand',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='basecommand',
            name='parameters',
            field=models.TextField(null=True),
        ),
    ]
