# Generated by Django 4.1.6 on 2023-03-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_alter_basecommand_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecommand',
            name='icon',
            field=models.ImageField(default='images/default_icon.jpg', upload_to='images/'),
        ),
    ]
