# Generated by Django 4.2 on 2023-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0017_alter_basescript_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecommand',
            name='executable_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='type',
            field=models.CharField(default='string', max_length=250),
            preserve_default=False,
        ),
    ]
