# Generated by Django 4.2 on 2023-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0017_alter_basescript_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecommand',
            name='command_exe_link',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
