# Generated by Django 4.2 on 2023-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0018_basecommand_command_exe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='type',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
