# Generated by Django 4.1.6 on 2023-06-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0018_basecommand_executable_url_parameters_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecommand',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='basescript',
            name='is_reviewed',
        ),
    ]
