# Generated by Django 4.1.6 on 2023-06-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0020_commandapproverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandapproverequest',
            name='user',
        ),
    ]
